---
env:
  node: true
  es2021: true

parserOptions:
  ecmaVersion: 2021
  sourceType: module

extends:
  - 'airbnb-base'
  - 'plugin:import/recommended'

rules:
  no-console: 0
  import/extensions: 0
